#define PRESSURE_ADDR 0x77 /*ADDRESS FOR BMP085 BOSCH BAROMETRIC PRESSURE SENSOR*/


#define GYRO_ADDR 0x69 /*ADDRESS FOR L3G4200D GYROSCOPE FROM ST MICRO*/


#define ACCEL_ADDR 0x53 /*ADDRESS FOR ADXL345 FROM ANALOG DEVICES*/
#define ACCEL_DEVID 0x00 /*READ ONLY*/
/*REGISTERS: 0x01 to 0x1C ARE RESERVED*/
#define ACCEL_THRESH_INACT   0x25 /**/
#define ACCEL_OFFSET_X   0x1E /*READ/WRITE*/
#define ACCEL_OFFSET_Y   0x1F /*READ/WRITE*/
#define ACCEL_OFFSET_Z   0x20 /*READ/WRITE*/

#define ACCEL_WRITE_ADDR  0xA6 /*READ/WRITE*/
#define ACCEL_READ_ADDR   0xA7 /*READ/WRITE*/

/*ACCELEROMETER THRESHOLD AND CONTROL REGISTERS:*/
#define ACCEL_THRESH_TAP     0x1D /*READ/WRITE*/
#define ACCEL_THRESH_DUR     0x21 /*READ/WRITE*/
#define ACCEL_THRESH_LATENCY 0x22 /*READ/WRITE*/
#define ACCEL_THRESH_WINDOW  0x23 /*READ/WRITE*/
#define ACCEL_ACTIVITY       0x24 /*READ/WRITE*/
#define ACCEL_THRESH_INACT   0x25 /*READ/WRITE*/
#define ACCEL_TIME_INACT     0x26 /*READ/WRITE*/
#define ACCEL_INACT_CTL      0x27 /*READ/WRITE, MAX: 255 Seconds ~4.25 mins*/
#define ACCEL_THRESH_FFALL   0x28 /*READ/WRITE*/
#define ACCEL_TIME_FFALL     0x29 /*READ/WRITE*/
#define ACCEL_TAP_AXES       0x2A /*READ/WRITE*/
#define ACCEL_TAP_ACT_STATUS 0x2B /*READ ONLY*/
#define ACCEL_BW_RATE        0x2C /*READ/WRITE*/
#define ACCEL_POWER_CTRL     0x2D /*READ/WRITE*/
#define ACCEL_INT_EN_ADDR    0x2E /*READ/WRITE*/
#define ACCEL_INT_MAP        0x2F /*READ/WRITE*/
#define ACCEL_INT_SRC        0x30 /*READ ONLY : INTERRUPT SOURCE*/
#define ACCEL_DATA_FMT       0X31 /*READ/WRITE, SELF_TEST BIT IS LOCATED HERE, BIT: */

/*ACCELEROMETER DATA REGISTERS:*/
#define ACCEL_DATA_X0        0x32 /*READ ONLY*/
#define ACCEL_DATA_X1        0x33 /*READ ONLY*/

#define ACCEL_DATA_Y0        0x34 /*READ ONLY*/
#define ACCEL_DATA_Y1        0x35 /*READ ONLY*/

#define ACCEL_DATA_Z0        0x36 /*READ ONLY*/
#define ACCEL_DATA_Z1        0x37 /*READ ONLY*/

#define ACCEL_FIFO_CTRL      0x38 /*WATERMARK, CLEARED AUTOMATICALLY WHEN FIFO READ*/
#define ACCEL_FIFO_STATUS    0x39 /*READ ONLY*/

/*PARAMETERS:*/
#define NUM_SAMPLES ((uint8_t)10)
#define ACCEL_RATE_100KHZ ((uint8_t *)0x0A)
#define ACCEL_MODE_16G    ((uint8_t *)0x03)


/*INIT Commands:*/
#define SELF_TEST_ON ((uint8_t *)0x8B)
#define SELF_TEST_OFF ((uint8_t *)0x0B)
#define ACCEL_FIFO_INIT ((uint8_t*)0x02)

/*ACCELEROMETER FUNCTIONS*/
//INIT_ACCEL();

/*READ FROM EACH AXIS*/
//READ_ACCELX();
//READ_ACCELY();
//READ_ACCELZ();
